Lesson 1.3 - done (fixed bugs and add diff ex)
ponomareva-a-o/homeworks pull request #3
Opened 2021-09-13 19:48 UTC by ponomareva-a-o

2021-09-14 15:22 UTC, DisterRU approved these changes
Хорошо, но можешь лучше. :)

2021-09-14 15:22 UTC, DisterRU commented on src/pro/sky/java/course1/lesson3/Main.java
> +        if (yearDivisible4 || yearDivisible100 || yearDivisible400) {
Вместо ИЛИ должны быть И.
Получится, что если код кратен 4, то он в любом случае високосный, тогда именно кратные 100 года будут високосными.

2021-09-14 15:22 UTC, DisterRU commented on src/pro/sky/java/course1/lesson3/Main.java
>          }
Стоит посмотреть второй QA вебинар.
Я там показывал, почему так делать не очень хорошо.
Если вкратце, то нужно сделать из этого два отдельных блока иф, которые инкрементируют дни.
Рекомендую посмотреть.

2021-09-14 15:22 UTC, DisterRU commented on src/pro/sky/java/course1/lesson3/Main.java
> +            finalRate = rate;
Тоже стоит использовать ту переменную, что и в прошлых блоках.

2021-09-14 15:33 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
> +        boolean yearDivisible100 = (year % 100 == 0);
(((( я погуляла, почему каждый сотый не является , надо бы описать в задании это более явно , исправила

2021-09-14 15:33 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
> +        if (yearDivisible4 || yearDivisible100 || yearDivisible400) {
^^^

2021-09-19 13:52 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
> +            rate = baseRate;
убрала переменную baseRate, присвоила переменной rate = 10 , убрала в первом блоке последний else

2021-09-19 14:02 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
> +        double finalLimit;
убрала переменную finalLimit, убрала во втором блоке последний else

2021-09-19 14:04 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
> +            finalRate = rate;
сделала

2021-09-19 14:06 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
>          }
я его посмотрела, но так и не очень поняла , сделала по-другому , но тоже получается костыльное, если вдруг сроки доставки по каким-то причинам для обозначенных интервалов изменятся

2021-09-20 10:33 UTC, DisterRU requested changes
Нужно внести небольшие правки и доработать задачу с днями.

2021-09-20 10:33 UTC, DisterRU commented on src/pro/sky/java/course1/lesson3/Main.java
> +        boolean yearDivisible100 = (year % 100 == 0);
Да без разницы, что там и почему.
Главное, что не является.
И это указано. :)

2021-09-20 10:33 UTC, DisterRU commented on src/pro/sky/java/course1/lesson3/Main.java
> +        if ((yearDivisible4 && !yearDivisible100) || (yearDivisible100 && yearDivisible400)) {
year % 4 == 0 && year % 100 != 0 || year % 400 == 0
Тут три условия, а у тебя получилось 4

2021-09-20 10:33 UTC, DisterRU commented on src/pro/sky/java/course1/lesson3/Main.java
>          }
Всё ещё не соответствует тому, что было показано на QA вебинаре.
Что будет, если между 20 и 30 появится ещё один день?
Нужно написать так, чтобы в любой момент можно было вставить ещё один доп блок.
Т.е. твои подсчитанные в голове дни (что больше 60 должны накидывать 2 дня) сломаются.

2021-09-20 10:33 UTC, DisterRU commented on src/pro/sky/java/course1/lesson3/Main.java
> +            limit = limit * 1.2;
limit *= 1.2

2021-09-20 10:33 UTC, DisterRU commented on src/pro/sky/java/course1/lesson3/Main.java
> +            limit = limit * 1.5;
limit *= 1.5

2021-09-20 19:18 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
> +        if ((yearDivisible4 && !yearDivisible100) || (yearDivisible100 && yearDivisible400)) {
1 И 2 ИЛИ 3

то есть кратно 4 и не кратно 100 ИЛИ кратно 400

ну в целом вроде да, просто мои условия , мне показалось, более полная проверка, но, видимо, излишняя
поправила

2021-09-20 19:27 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
>          }
я поняла))))))) надо, чтобы ифы были независимые, блиин

2021-09-20 19:27 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
>          }
поправила

2021-09-20 19:29 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
> +            limit = limit * 1.2;
done

2021-09-20 19:29 UTC, ponomareva-a-o commented on src/pro/sky/java/course1/lesson3/Main.java
> +            limit = limit * 1.5;
done

2021-10-03 14:02 UTC, merged